/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicPengaduanIndexRouteImport } from './routes/_public/pengaduan/index'
import { Route as PublicLaporMeterIndexRouteImport } from './routes/_public/lapor-meter/index'
import { Route as PublicCekTagihanIndexRouteImport } from './routes/_public/cek-tagihan/index'
import { Route as DashboardTagihanIndexRouteImport } from './routes/_dashboard/tagihan/index'
import { Route as DashboardPencatatanIndexRouteImport } from './routes/_dashboard/pencatatan/index'
import { Route as DashboardPelangganIndexRouteImport } from './routes/_dashboard/pelanggan/index'
import { Route as DashboardOverviewIndexRouteImport } from './routes/_dashboard/overview/index'
import { Route as DashboardMapIndexRouteImport } from './routes/_dashboard/map/index'
import { Route as DashboardLaporanMandiriIndexRouteImport } from './routes/_dashboard/laporan-mandiri/index'
import { Route as DashboardLaporanHarianIndexRouteImport } from './routes/_dashboard/laporan-harian/index'
import { Route as DashboardDrdIndexRouteImport } from './routes/_dashboard/drd/index'
import { Route as AuthTwoFactorIndexRouteImport } from './routes/_auth/two-factor/index'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPengaduanIndexRoute = PublicPengaduanIndexRouteImport.update({
  id: '/pengaduan/',
  path: '/pengaduan/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLaporMeterIndexRoute = PublicLaporMeterIndexRouteImport.update({
  id: '/lapor-meter/',
  path: '/lapor-meter/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCekTagihanIndexRoute = PublicCekTagihanIndexRouteImport.update({
  id: '/cek-tagihan/',
  path: '/cek-tagihan/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DashboardTagihanIndexRoute = DashboardTagihanIndexRouteImport.update({
  id: '/tagihan/',
  path: '/tagihan/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPencatatanIndexRoute =
  DashboardPencatatanIndexRouteImport.update({
    id: '/pencatatan/',
    path: '/pencatatan/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPelangganIndexRoute = DashboardPelangganIndexRouteImport.update({
  id: '/pelanggan/',
  path: '/pelanggan/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOverviewIndexRoute = DashboardOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMapIndexRoute = DashboardMapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLaporanMandiriIndexRoute =
  DashboardLaporanMandiriIndexRouteImport.update({
    id: '/laporan-mandiri/',
    path: '/laporan-mandiri/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLaporanHarianIndexRoute =
  DashboardLaporanHarianIndexRouteImport.update({
    id: '/laporan-harian/',
    path: '/laporan-harian/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDrdIndexRoute = DashboardDrdIndexRouteImport.update({
  id: '/drd/',
  path: '/drd/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthTwoFactorIndexRoute = AuthTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/two-factor/': typeof AuthTwoFactorIndexRoute
  '/drd/': typeof DashboardDrdIndexRoute
  '/laporan-harian/': typeof DashboardLaporanHarianIndexRoute
  '/laporan-mandiri/': typeof DashboardLaporanMandiriIndexRoute
  '/map/': typeof DashboardMapIndexRoute
  '/overview/': typeof DashboardOverviewIndexRoute
  '/pelanggan/': typeof DashboardPelangganIndexRoute
  '/pencatatan/': typeof DashboardPencatatanIndexRoute
  '/tagihan/': typeof DashboardTagihanIndexRoute
  '/cek-tagihan/': typeof PublicCekTagihanIndexRoute
  '/lapor-meter/': typeof PublicLaporMeterIndexRoute
  '/pengaduan/': typeof PublicPengaduanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/two-factor': typeof AuthTwoFactorIndexRoute
  '/drd': typeof DashboardDrdIndexRoute
  '/laporan-harian': typeof DashboardLaporanHarianIndexRoute
  '/laporan-mandiri': typeof DashboardLaporanMandiriIndexRoute
  '/map': typeof DashboardMapIndexRoute
  '/overview': typeof DashboardOverviewIndexRoute
  '/pelanggan': typeof DashboardPelangganIndexRoute
  '/pencatatan': typeof DashboardPencatatanIndexRoute
  '/tagihan': typeof DashboardTagihanIndexRoute
  '/cek-tagihan': typeof PublicCekTagihanIndexRoute
  '/lapor-meter': typeof PublicLaporMeterIndexRoute
  '/pengaduan': typeof PublicPengaduanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_auth/two-factor/': typeof AuthTwoFactorIndexRoute
  '/_dashboard/drd/': typeof DashboardDrdIndexRoute
  '/_dashboard/laporan-harian/': typeof DashboardLaporanHarianIndexRoute
  '/_dashboard/laporan-mandiri/': typeof DashboardLaporanMandiriIndexRoute
  '/_dashboard/map/': typeof DashboardMapIndexRoute
  '/_dashboard/overview/': typeof DashboardOverviewIndexRoute
  '/_dashboard/pelanggan/': typeof DashboardPelangganIndexRoute
  '/_dashboard/pencatatan/': typeof DashboardPencatatanIndexRoute
  '/_dashboard/tagihan/': typeof DashboardTagihanIndexRoute
  '/_public/cek-tagihan/': typeof PublicCekTagihanIndexRoute
  '/_public/lapor-meter/': typeof PublicLaporMeterIndexRoute
  '/_public/pengaduan/': typeof PublicPengaduanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/unauthorized'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/sign-up/'
    | '/two-factor/'
    | '/drd/'
    | '/laporan-harian/'
    | '/laporan-mandiri/'
    | '/map/'
    | '/overview/'
    | '/pelanggan/'
    | '/pencatatan/'
    | '/tagihan/'
    | '/cek-tagihan/'
    | '/lapor-meter/'
    | '/pengaduan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/unauthorized'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/two-factor'
    | '/drd'
    | '/laporan-harian'
    | '/laporan-mandiri'
    | '/map'
    | '/overview'
    | '/pelanggan'
    | '/pencatatan'
    | '/tagihan'
    | '/cek-tagihan'
    | '/lapor-meter'
    | '/pengaduan'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_public'
    | '/about'
    | '/unauthorized'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/reset-password/'
    | '/_auth/sign-up/'
    | '/_auth/two-factor/'
    | '/_dashboard/drd/'
    | '/_dashboard/laporan-harian/'
    | '/_dashboard/laporan-mandiri/'
    | '/_dashboard/map/'
    | '/_dashboard/overview/'
    | '/_dashboard/pelanggan/'
    | '/_dashboard/pencatatan/'
    | '/_dashboard/tagihan/'
    | '/_public/cek-tagihan/'
    | '/_public/lapor-meter/'
    | '/_public/pengaduan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pengaduan/': {
      id: '/_public/pengaduan/'
      path: '/pengaduan'
      fullPath: '/pengaduan/'
      preLoaderRoute: typeof PublicPengaduanIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/lapor-meter/': {
      id: '/_public/lapor-meter/'
      path: '/lapor-meter'
      fullPath: '/lapor-meter/'
      preLoaderRoute: typeof PublicLaporMeterIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/cek-tagihan/': {
      id: '/_public/cek-tagihan/'
      path: '/cek-tagihan'
      fullPath: '/cek-tagihan/'
      preLoaderRoute: typeof PublicCekTagihanIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_dashboard/tagihan/': {
      id: '/_dashboard/tagihan/'
      path: '/tagihan'
      fullPath: '/tagihan/'
      preLoaderRoute: typeof DashboardTagihanIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/pencatatan/': {
      id: '/_dashboard/pencatatan/'
      path: '/pencatatan'
      fullPath: '/pencatatan/'
      preLoaderRoute: typeof DashboardPencatatanIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/pelanggan/': {
      id: '/_dashboard/pelanggan/'
      path: '/pelanggan'
      fullPath: '/pelanggan/'
      preLoaderRoute: typeof DashboardPelangganIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/overview/': {
      id: '/_dashboard/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof DashboardOverviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/map/': {
      id: '/_dashboard/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof DashboardMapIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/laporan-mandiri/': {
      id: '/_dashboard/laporan-mandiri/'
      path: '/laporan-mandiri'
      fullPath: '/laporan-mandiri/'
      preLoaderRoute: typeof DashboardLaporanMandiriIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/laporan-harian/': {
      id: '/_dashboard/laporan-harian/'
      path: '/laporan-harian'
      fullPath: '/laporan-harian/'
      preLoaderRoute: typeof DashboardLaporanHarianIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/drd/': {
      id: '/_dashboard/drd/'
      path: '/drd'
      fullPath: '/drd/'
      preLoaderRoute: typeof DashboardDrdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/two-factor/': {
      id: '/_auth/two-factor/'
      path: '/two-factor'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof AuthTwoFactorIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
  AuthTwoFactorIndexRoute: typeof AuthTwoFactorIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
  AuthTwoFactorIndexRoute: AuthTwoFactorIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDrdIndexRoute: typeof DashboardDrdIndexRoute
  DashboardLaporanHarianIndexRoute: typeof DashboardLaporanHarianIndexRoute
  DashboardLaporanMandiriIndexRoute: typeof DashboardLaporanMandiriIndexRoute
  DashboardMapIndexRoute: typeof DashboardMapIndexRoute
  DashboardOverviewIndexRoute: typeof DashboardOverviewIndexRoute
  DashboardPelangganIndexRoute: typeof DashboardPelangganIndexRoute
  DashboardPencatatanIndexRoute: typeof DashboardPencatatanIndexRoute
  DashboardTagihanIndexRoute: typeof DashboardTagihanIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDrdIndexRoute: DashboardDrdIndexRoute,
  DashboardLaporanHarianIndexRoute: DashboardLaporanHarianIndexRoute,
  DashboardLaporanMandiriIndexRoute: DashboardLaporanMandiriIndexRoute,
  DashboardMapIndexRoute: DashboardMapIndexRoute,
  DashboardOverviewIndexRoute: DashboardOverviewIndexRoute,
  DashboardPelangganIndexRoute: DashboardPelangganIndexRoute,
  DashboardPencatatanIndexRoute: DashboardPencatatanIndexRoute,
  DashboardTagihanIndexRoute: DashboardTagihanIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicCekTagihanIndexRoute: typeof PublicCekTagihanIndexRoute
  PublicLaporMeterIndexRoute: typeof PublicLaporMeterIndexRoute
  PublicPengaduanIndexRoute: typeof PublicPengaduanIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicCekTagihanIndexRoute: PublicCekTagihanIndexRoute,
  PublicLaporMeterIndexRoute: PublicLaporMeterIndexRoute,
  PublicPengaduanIndexRoute: PublicPengaduanIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
