/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as PublicPengaduanIndexRouteImport } from './routes/_public/pengaduan/index'
import { Route as PublicLaporMeterIndexRouteImport } from './routes/_public/lapor-meter/index'
import { Route as PublicCekTagihanIndexRouteImport } from './routes/_public/cek-tagihan/index'
import { Route as DashboardTagihanIndexRouteImport } from './routes/_dashboard/tagihan/index'
import { Route as DashboardPencatatanIndexRouteImport } from './routes/_dashboard/pencatatan/index'
import { Route as DashboardPelangganIndexRouteImport } from './routes/_dashboard/pelanggan/index'
import { Route as DashboardOverviewIndexRouteImport } from './routes/_dashboard/overview/index'
import { Route as DashboardMapIndexRouteImport } from './routes/_dashboard/map/index'
import { Route as DashboardLaporanMandiriIndexRouteImport } from './routes/_dashboard/laporan-mandiri/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPengaduanIndexRoute = PublicPengaduanIndexRouteImport.update({
  id: '/pengaduan/',
  path: '/pengaduan/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLaporMeterIndexRoute = PublicLaporMeterIndexRouteImport.update({
  id: '/lapor-meter/',
  path: '/lapor-meter/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCekTagihanIndexRoute = PublicCekTagihanIndexRouteImport.update({
  id: '/cek-tagihan/',
  path: '/cek-tagihan/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DashboardTagihanIndexRoute = DashboardTagihanIndexRouteImport.update({
  id: '/tagihan/',
  path: '/tagihan/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPencatatanIndexRoute =
  DashboardPencatatanIndexRouteImport.update({
    id: '/pencatatan/',
    path: '/pencatatan/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPelangganIndexRoute = DashboardPelangganIndexRouteImport.update({
  id: '/pelanggan/',
  path: '/pelanggan/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOverviewIndexRoute = DashboardOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMapIndexRoute = DashboardMapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLaporanMandiriIndexRoute =
  DashboardLaporanMandiriIndexRouteImport.update({
    id: '/laporan-mandiri/',
    path: '/laporan-mandiri/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/laporan-mandiri/': typeof DashboardLaporanMandiriIndexRoute
  '/map/': typeof DashboardMapIndexRoute
  '/overview/': typeof DashboardOverviewIndexRoute
  '/pelanggan/': typeof DashboardPelangganIndexRoute
  '/pencatatan/': typeof DashboardPencatatanIndexRoute
  '/tagihan/': typeof DashboardTagihanIndexRoute
  '/cek-tagihan/': typeof PublicCekTagihanIndexRoute
  '/lapor-meter/': typeof PublicLaporMeterIndexRoute
  '/pengaduan/': typeof PublicPengaduanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/laporan-mandiri': typeof DashboardLaporanMandiriIndexRoute
  '/map': typeof DashboardMapIndexRoute
  '/overview': typeof DashboardOverviewIndexRoute
  '/pelanggan': typeof DashboardPelangganIndexRoute
  '/pencatatan': typeof DashboardPencatatanIndexRoute
  '/tagihan': typeof DashboardTagihanIndexRoute
  '/cek-tagihan': typeof PublicCekTagihanIndexRoute
  '/lapor-meter': typeof PublicLaporMeterIndexRoute
  '/pengaduan': typeof PublicPengaduanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_dashboard/laporan-mandiri/': typeof DashboardLaporanMandiriIndexRoute
  '/_dashboard/map/': typeof DashboardMapIndexRoute
  '/_dashboard/overview/': typeof DashboardOverviewIndexRoute
  '/_dashboard/pelanggan/': typeof DashboardPelangganIndexRoute
  '/_dashboard/pencatatan/': typeof DashboardPencatatanIndexRoute
  '/_dashboard/tagihan/': typeof DashboardTagihanIndexRoute
  '/_public/cek-tagihan/': typeof PublicCekTagihanIndexRoute
  '/_public/lapor-meter/': typeof PublicLaporMeterIndexRoute
  '/_public/pengaduan/': typeof PublicPengaduanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/unauthorized'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/laporan-mandiri/'
    | '/map/'
    | '/overview/'
    | '/pelanggan/'
    | '/pencatatan/'
    | '/tagihan/'
    | '/cek-tagihan/'
    | '/lapor-meter/'
    | '/pengaduan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/unauthorized'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/laporan-mandiri'
    | '/map'
    | '/overview'
    | '/pelanggan'
    | '/pencatatan'
    | '/tagihan'
    | '/cek-tagihan'
    | '/lapor-meter'
    | '/pengaduan'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_public'
    | '/about'
    | '/login'
    | '/unauthorized'
    | '/auth/_layout'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_dashboard/laporan-mandiri/'
    | '/_dashboard/map/'
    | '/_dashboard/overview/'
    | '/_dashboard/pelanggan/'
    | '/_dashboard/pencatatan/'
    | '/_dashboard/tagihan/'
    | '/_public/cek-tagihan/'
    | '/_public/lapor-meter/'
    | '/_public/pengaduan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pengaduan/': {
      id: '/_public/pengaduan/'
      path: '/pengaduan'
      fullPath: '/pengaduan/'
      preLoaderRoute: typeof PublicPengaduanIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/lapor-meter/': {
      id: '/_public/lapor-meter/'
      path: '/lapor-meter'
      fullPath: '/lapor-meter/'
      preLoaderRoute: typeof PublicLaporMeterIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/cek-tagihan/': {
      id: '/_public/cek-tagihan/'
      path: '/cek-tagihan'
      fullPath: '/cek-tagihan/'
      preLoaderRoute: typeof PublicCekTagihanIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_dashboard/tagihan/': {
      id: '/_dashboard/tagihan/'
      path: '/tagihan'
      fullPath: '/tagihan/'
      preLoaderRoute: typeof DashboardTagihanIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/pencatatan/': {
      id: '/_dashboard/pencatatan/'
      path: '/pencatatan'
      fullPath: '/pencatatan/'
      preLoaderRoute: typeof DashboardPencatatanIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/pelanggan/': {
      id: '/_dashboard/pelanggan/'
      path: '/pelanggan'
      fullPath: '/pelanggan/'
      preLoaderRoute: typeof DashboardPelangganIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/overview/': {
      id: '/_dashboard/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof DashboardOverviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/map/': {
      id: '/_dashboard/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof DashboardMapIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/laporan-mandiri/': {
      id: '/_dashboard/laporan-mandiri/'
      path: '/laporan-mandiri'
      fullPath: '/laporan-mandiri/'
      preLoaderRoute: typeof DashboardLaporanMandiriIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardLaporanMandiriIndexRoute: typeof DashboardLaporanMandiriIndexRoute
  DashboardMapIndexRoute: typeof DashboardMapIndexRoute
  DashboardOverviewIndexRoute: typeof DashboardOverviewIndexRoute
  DashboardPelangganIndexRoute: typeof DashboardPelangganIndexRoute
  DashboardPencatatanIndexRoute: typeof DashboardPencatatanIndexRoute
  DashboardTagihanIndexRoute: typeof DashboardTagihanIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLaporanMandiriIndexRoute: DashboardLaporanMandiriIndexRoute,
  DashboardMapIndexRoute: DashboardMapIndexRoute,
  DashboardOverviewIndexRoute: DashboardOverviewIndexRoute,
  DashboardPelangganIndexRoute: DashboardPelangganIndexRoute,
  DashboardPencatatanIndexRoute: DashboardPencatatanIndexRoute,
  DashboardTagihanIndexRoute: DashboardTagihanIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicCekTagihanIndexRoute: typeof PublicCekTagihanIndexRoute
  PublicLaporMeterIndexRoute: typeof PublicLaporMeterIndexRoute
  PublicPengaduanIndexRoute: typeof PublicPengaduanIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicCekTagihanIndexRoute: PublicCekTagihanIndexRoute,
  PublicLaporMeterIndexRoute: PublicLaporMeterIndexRoute,
  PublicPengaduanIndexRoute: PublicPengaduanIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
